# Windows (https://github.com/travis-ci-tester/toolchain-table)

environment:
  matrix:
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  TOOLCHAIN: "vs-15-2017-cxx17"
    #  EXAMPLE: 01-executable
    #  CONFIG: Release

    #- TOOLCHAIN: "ninja-vs-12-2013-win64"
    #  EXAMPLE: 01-executable
    #  CONFIG: Release

    #- TOOLCHAIN: "nmake-vs-12-2013-win64"
    #  EXAMPLE: 01-executable
    #  CONFIG: Release

    #- TOOLCHAIN: "vs-12-2013"
    #  EXAMPLE: 01-executable
    #  CONFIG: Release

    #- TOOLCHAIN: "vs-14-2015"
    #  EXAMPLE: 01-executable
    #  CONFIG: Release

    #- TOOLCHAIN: "vs-14-2015"
    #  EXAMPLE: 02-library
    #  CONFIG: Release

    #- TOOLCHAIN: "vs-14-2015"
    #  EXAMPLE: 03-shared-link
    #  CONFIG: Release

    #- TOOLCHAIN: "mingw"
    #  EXAMPLE: 01-executable
    #  CONFIG: Release

    #- TOOLCHAIN: "mingw-cxx14"
    #  EXAMPLE: 01-executable
    #  CONFIG: Release
    #  CMAKE_MAKE_PROGRAM: mingw32-make.exe
    #  MINGW_PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
    #  ADD_TO_PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin 

    #- TOOLCHAIN: "mingw-cxx17"
    #  EXAMPLE: 01-executable
    #  CONFIG: Release
    #  CMAKE_MAKE_PROGRAM: mingw32-make.exe
    #  MINGW_PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
    #  ADD_TO_PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin 

    - TOOLCHAIN: "msys"
      EXAMPLE: 01-executable
      CONFIG: Release

    - TOOLCHAIN: "msys-cxx14"
      EXAMPLE: 01-executable
      CONFIG: Release

    #- TOOLCHAIN: "msys-cxx17"
    #  EXAMPLE: 01-executable
    #  CONFIG: Release
    #  CMAKE_MAKE_PROGRAM: mingw32-make.exe
    #  MSYS_PATH: C:\msys64\mingw64\bin
    #  ADD_TO_PATH: C:\msys64\mingw64\bin


install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests

  # Install dependencies (CMake, Ninja)
  - cmd: set POLLY_SOURCE_DIR=%cd%
  - cmd: python %POLLY_SOURCE_DIR%\bin\install-ci-dependencies.py

  # Tune locations
  - cmd: set PATH=%cd%\_ci\cmake\bin;%PATH%
  - cmd: set PATH=%cd%\_ci\ninja;%PATH%
  - cmd: set PATH=%PATH%;%ADD_TO_PATH%

  # Remove entry with sh.exe from PATH to fix error with MinGW toolchain
  # (For MinGW make to work correctly sh.exe must NOT be in your path)
  # * http://stackoverflow.com/a/3870338/2288008
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # Use MinGW from Qt tools because version is higher
  # * http://www.appveyor.com/docs/installed-software#qt
  - cmd: set MINGW_PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

  # MSYS2 location
  - cmd: set MSYS_PATH=C:\msys64\usr\bin
  - cmd: dir %MSYS_PATH% 
  - cmd: cmd /c %MSYS_PATH%\uname.exe -a 

build_script:
  - cmd: python %POLLY_SOURCE_DIR%\bin\build.py --home examples/%EXAMPLE% --toolchain %TOOLCHAIN% --config %CONFIG% --verbose --clear --install --test 

branches:
  except:
    - /^pr\..*/
